{"uuid": "0c858621-6f23-4498-b1c2-b4ce68db7462", "children": ["9d13d013-9430-4455-a26a-cb5f13e74e45", "3b5fd0b0-c4c8-42ee-a4d4-84acb0d2bad8", "ddb42872-6b3c-4982-9d19-38c540ea3a7b"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device.\n\n", "trace": "  File \"D:\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"D:\\Users\\Administrator\\code\\PycharmProjects\\appium\\conftest.py\", line 11, in driver\n    driver = webdriver.Remote(command_executor, desired_caps)\n  File \"D:\\python\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 151, in __init__\n    proxy\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\python\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 227, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1587362188628, "stop": 1587362211452}], "start": 1587362188628, "stop": 1587362211921}