{"uuid": "f09d3e3f-8efb-433f-b1d6-f25b4d4556ce", "children": ["b0c997c9-19fc-4c8c-a1ab-0815a6170896", "c2ccacd5-5ba5-41d4-83e8-68b0fb83d79d", "ba9ce6bd-a2f6-4fd2-a7f9-ef4c4bda69ac"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device.\n\n", "trace": "  File \"D:\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"D:\\Users\\Administrator\\code\\PycharmProjects\\appium\\conftest.py\", line 11, in driver\n    driver = webdriver.Remote(command_executor, desired_caps)\n  File \"D:\\python\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 151, in __init__\n    proxy\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\python\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 227, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1587361869143, "stop": 1587361891526}], "start": 1587361869143, "stop": 1587361891923}